FROM python:3.11-slim
WORKDIR /app
COPY services/bat-payment-service/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY services/bat-payment-service/ .
COPY middleware ./middleware
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
