FROM python:3.11-slim
WORKDIR /app
COPY services/bat-payment-service/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY services/bat-payment-service/ .
CMD uvicorn main:app --host $APP_HOST --port $APP_PORT
