services:
  catalog:
    env_file:
      - .env
    build: 
      context: .
      dockerfile: services/bat-catalog-service/dockerfile
    container_name: catalog
    ports:
      - "${CATALOG_HOST_PORT}:${APP_PORT}"
    
  order:
    env_file:
      - .env
    build: 
      context: .
      dockerfile: services/bat-order-service/dockerfile
    container_name: order
    ports:
      - "${ORDER_HOST_PORT}:${APP_PORT}"
    depends_on:
      - catalog
      - redis
  
  payment:
    env_file:
      - .env
    build: 
      context: .
      dockerfile: services/bat-payment-service/dockerfile
    container_name: payment
    ports:
      - "${PAYMENT_HOST_PORT}:${APP_PORT}"
    depends_on:
      - catalog
    
  notification:
    env_file:
      - .env
    build: 
      context: .
      dockerfile: services/bat-notification-service/dockerfile
    container_name: notification
    ports:
      - "${NOTIFICATION_HOST_PORT}:${APP_PORT}"
    depends_on:
      - redis
    
  auth:
    env_file:
      - .env
    build: 
      context: .
      dockerfile: services/bat-auth-service/dockerfile
    container_name: auth
    ports:
      - "${AUTH_HOST_PORT}:${APP_PORT}"

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "${REDIS_HOST_PORT}:${REDIS_PORT}"
