global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'bat-auth-service'
    static_configs:
      - targets: ['bat-auth-service:8000']

  - job_name: 'bat-catalog-service'
    static_configs:
      - targets: ['bat-catalog-service:8000']

  - job_name: 'bat-order-service'
    static_configs:
      - targets: ['bat-order-service:8000']

  - job_name: 'bat-payment-service'
    static_configs:
      - targets: ['bat-payment-service:8000']

  - job_name: 'bat-notification-service'
    static_configs:
      - targets: ['bat-notification-service:8000']
