FROM python:3.11-slim
WORKDIR /app
COPY services/bat-notification-service/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY services/bat-notification-service/ .
COPY middleware ./middleware
CMD uvicorn main:app --host $APP_HOST --port $APP_PORT
